/*
Vapor Test Suite
2001: Catch derived class

- output
"Hello exception world." From MyException2!
*/

using Core;

class MyException: Exception
{
	public String message;

	public (String message)
	{
		this.message = message;
	}
}

class MyException2: MyException
{
	public (String message)
	{
		this.message = "\"" + message + "\" From MyException2!";
	}
}

class Test
{
	public static Main()
	{
		try
		{
			throw new MyException2("Hello exception world.");
		}
		catch (MyException e)
		{
			Console.WriteLine(e.message);
		}
	}
}
